[package]
name = "ue14500-toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
bitbit = "0.2"
chonk = "0.5"
infer = "0.6"
prettytable-rs = "0.8"

[dependencies.clap]
version = "3.0"
features = ["derive"]